platform :ios, '15.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'EnglishSentence' do
  use_frameworks!

  pod 'SnapKit'
  pod 'EasyTipView'
  pod 'AMPopTip'
  pod 'SDWebImage'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
